### ISSUE TITLE
хачу стать пирикупом авита

### ISSUE THREAD

**Issue by Tripl0Color** [vas-ya-pupkin/avito_youla_search#1]
Traceback (most recent call last):
  File "C:\Users\tripl\Desktop\avito_youla_search-master\main.py", line 26, in <module>
    items = y.check_new()
  File "C:\Users\tripl\Desktop\avito_youla_search-master\youla.py", line 31, in check_new
    return self._extract_ads(resp)
  File "C:\Users\tripl\Desktop\avito_youla_search-master\youla.py", line 35, in _extract_ads
    soup = BeautifulSoup(html, 'lxml')
  File "C:\Users\tripl\AppData\Local\Programs\Python\Python39\lib\site-packages\bs4\__init__.py", line 245, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by ffffaust** [comment]
requirements.txt обновлены + пофикшен поиск по авито
